### ISSUE TITLE
/etc/mailer.conf in TRIBsys-net-mailwrapper wrong

### ISSUE THREAD

**Issue by bamdadkhan** [tribblix/build#8]
Hello,

/etc/mailer.conf in TRIBsys-net-mailwrapper should contain the following for sendmail to work properly:

```
#
# This file configures mailwrapper(1M).
# For details see mailer.conf(4).
# The following configuration is correct for sendmail(1M).
#

sendmail        /usr/lib/smtp/sendmail/sendmail
newaliases      /usr/lib/smtp/sendmail/sendmail
mailq           /usr/lib/smtp/sendmail/mailq

```
Instead it has this for dma:

```
#
# This file configures mailwrapper(1M).
# For details see mailer.conf(4).
# The following configuration is correct for dma(1M).
#

sendmail        /usr/lib/smtp/dma/dma
newaliases      /usr/lib/smtp/dma/dma
mailq           /usr/lib/smtp/dma/dma
```

Since the default configuration has sendmail installed, this file should represent that also.

**Comment by ptribble** [comment]
This is on omnitribblix. You're right - OmniOSce have customized this for their distro (which does have dma rather than sendmail), so I need to fix this back to Tribblix defaults. I'll do that for the next release.

Thanks for reporting this!

**Comment by ptribble** [comment]
Build scripts corrected
https://github.com/tribblix/tribblix-build/commit/55faadb96b01f2fd6949cfda86d93cf3e5e1f5bb
